base/urls.py
from django.conf.urls import url
import base.views
urlpatterns = [
	url(r'^$', base.views.homeView),
    url(r'^configChannels/', base.views.configChannels),
    url(r'^addTerminals/', base.views.addTerminals),
    url(r'^editTerminals/(?P<terminalID>\d+)/$', base.views.editTerminals),
    url(r'^deleteTerminal/(?P<terminalID>\d+)/$', base.views.deleteTerminal),
    url(r'^configChannel/(?P<channelID>\d+)/$', base.views.configChannel),
    url(r'^configChannel/(?P<channelID>\d+)/(?P<channelNum>\d+)/$', base.views.configChannelWithNum),
    url(r'^configPolling/(?P<channelID>\d+)/(?P<channelNum>\d+)/$', base.views.configPolling),

	url(r'^hsInterface/', base.views.hsInterface),
]

config/urls.py
from django.conf.urls import url
import config.views

urlpatterns = [
	url(r'^textStyle/', config.views.textStyleView),
	url(r'^getMonitorInfo/', config.views.getMonitorInfo),
	url(r'^configSystem/', config.views.configSystem),
	url(r'^log/', config.views.logView),
	url(r'^exportUserLogAsCSV/$', config.views.exportUserLogAsCSV),
    url(r'^clearUserLog/$', config.views.clearUserLog),
]

lTvsWeb/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import base.views
urlpatterns = [
	url(r'^$', base.views.homeView),
    # url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('userena.urls')),  
	url(r'^sdt-hts/', include('base.urls')),
	url(r'^sdt-hts/', include('config.urls')),    
]

config/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class registerStatus(models.Model):
	resgisterStatus = models.BooleanField(default=False,verbose_name=u"系统注册状态")

class debugStatus(models.Model):
	debugStatus = models.BooleanField(default=False,verbose_name=u"是否记录调试日志")

class userLog(models.Model):
	user = models.CharField(max_length=3000)
	date = models.DateTimeField(auto_now=True)
	target = models.CharField(max_length=3000)
	content = models.CharField(max_length=3000)

class packetsLostInfo(models.Model):
	terminalName = models.CharField(max_length=300)
	latestLostDate = models.CharField(max_length=300)
	lostNumbers = models.IntegerField(default = 0)
	totalPacketNumbers = models.IntegerField(default = 0)
	status = models.BooleanField(default=False,verbose_name=u"是否有效")

class packetGrepper(models.Model):
	ip = models.GenericIPAddressField(unique=True,max_length=200,blank=False,null=False,verbose_name=u"IP",default="192.168.1.1")
	active = models.BooleanField(default=False,verbose_name=u"是否启用抓包服务器")
class textStyle(models.Model):
	textSize = models.IntegerField(default = 1)
	location = models.IntegerField(default = 0)
	color = models.IntegerField(default = 0)
	showFps = models.BooleanField(default=True,verbose_name=u"是否Show FPS")

config/forms.py
# -*- coding: UTF-8 -*-
from base.models import *
from config.models import *
from django.forms import ModelForm,ValidationError,TextInput
from django import forms

class textStyleForm(ModelForm):
    def __init__(self,*args,**kwargs):
        super(textStyleForm,self).__init__(*args,**kwargs)
        SIZECHOICES = [('0','small'),
        ('1','medium'),
        ('2','large')
        ]
        LOCATIONCHOICES = [('0','left top'),
        ('1','left bottom'),
        ]
        COLORCHOICES = [('0','color 1'),
        ('1','color 2'),
        ('2','color 3'),
        ('3','color 4'),
        ('4','color 5'),
        ]
        self.fields['textSize'] = forms.ChoiceField(label="textSize123",initial=('1','medium'),choices=SIZECHOICES,required=True)
        self.fields['location'] = forms.ChoiceField(label="location",choices=LOCATIONCHOICES,initial=('5','right bottom'),required=True)
        self.fields['color'] = forms.ChoiceField(label="color",choices=COLORCHOICES,initial=('0','color 1'),required=True)
        self.fields['showFps'] = forms.BooleanField(label="show FPS",required=False)
    class Meta:
        model = textStyle
        fields = '__all__'
        # widgets = {
        # 'textSize':TextInput(attrs={'class':'text-input small-input',}),
        # 'location':TextInput(attrs={'class':'text-input small-input',}),
        # }

config/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from base.models import *
from config.models import *
from config.forms import *
from django.http import HttpResponse, HttpResponseServerError
from django.http import HttpResponseRedirect

import re,os
import subprocess
from django.core import serializers
import os
import zipfile
import StringIO
import datetime
import base.hvs_pb2
from socket import *
# Create your views here.




def handelDevice(devMsg, gpuCount,monitorList):
    devDict = {'gpuSeq': gpuCount}
    devInfoList = re.split('\n', devMsg)
    for item in devInfoList:
        if len(item) == 0 or item == '\n':
            continue
        col = re.split(':', item)
        devDict[(col[0]).strip()] = col[1]
    monitorList.append(devDict)


dustMsgPat = '  Name.*\n.*\n.*\n.*Number of Display Devices: \d+\n'

deviceSplitPat = '  Display Device \d+ \(TV-\d+\):\n'


def handelGpu(gpuMsg, gpuCount,monitorList):
    # print gpuMsg
    result = re.sub(dustMsgPat, '', gpuMsg)
    # print "result= \n",(result)
    result1 = re.split(deviceSplitPat, result)
    for dev in result1:
        if len(dev) == 0:
            continue
        handelDevice(dev, gpuCount,monitorList)

def checkMonitor():
    output = subprocess.Popen('nvidia-xconfig --query-gpu-info', \
                              shell=True, \
                              stdout=subprocess.PIPE).communicate()[0]
    splitpat = 'GPU #\d+:\n'

    res0 = re.sub('Number of GPUs: \d+', '', output)
    res1 = re.sub('\n\n', '\n', res0)
    res2 = re.split(splitpat, res1)
    monitorList = []
    count = 0
    for gpu in res2:
        if len(gpu) == 0 or gpu == '\n':
            continue
        handelGpu(gpu, count,monitorList)
        count += 1
    i = 0
    print monitorList
    channel.objects.all().update(active=False)
    for item in monitorList:
        if channel.objects.filter(pk = (int(i)+1)).count() != 0:
            cn = channel.objects.get(pk = (int(i)+1))
            cn.name = u"通道"+str(i+1)
            cn.monitorName = monitorList[i]['EDID Name']
            cn.resolution = monitorList[i]['Preferred Width']+monitorList[i]['Preferred Height']
            cn.GPUSeq = monitorList[i]['gpuSeq']
            cn.freshRate = monitorList[i]['Preferred VertRefresh']
            cn.active = True
            cn.save()
            i+=1
    return monitorList

#-----------------------------------------------------------------------------------#

@login_required
@csrf_exempt
def getMonitorInfo(request):
    if request.POST:
        try:
            ret=checkMonitor()
            print ret
            if ret != False:
                return HttpResponse(u"刷新显示器成功")
            else:
                print e
                raise Exception(u"未知错误！")
        except Exception as e:
            return HttpResponse(u"刷新显示器not成功")

    elif request.GET:
        # 初始化
        if channel.objects.all().count() == 0:
            for i in range(8):
                channelInstance = channel(pk = int(i+1),name = u"通道"+str(i+1), saperateNumber=4, content=" ",polling=False,pollingPos="1:-1, 2:-1, 3:-1, 4:-1, 5:-1, 6:-1, 7:-1, 8:-1, 9:-1, 10:-1, 11:-1, 12:-1, 13:-1, 14:-1, 15:-1, 16:-1, 17:-1, 18:-1, 19:-1, 20:-1,")
                channelInstance.save()
        try:
            ret = checkMonitor()
            channelList = channel.objects.filter(active = True)
            print channelList
            json_reply = serializers.serialize("json",channelList)
            return HttpResponse(json_reply)
        except Exception as e:
            print e
            return HttpResponse(u"刷新显示器not成功")
    return render(request,'config/getMonitorInfo.html')

import os

@login_required
@csrf_exempt
def configSystem(request):
    if request.POST:
        if request.POST.__contains__("resetDatabase")==True and request.POST['resetDatabase'] == 'True':
            print "RESET"
            userLogInstance = userLog(user= request.user,target=u'系统',content=u'重置数据库')
            userLogInstance.save()
            shutil.copyfile("../db.sqlite3","./db.sqlite3")
            return HttpResponseRedirect('/sdt-hts/')
        if request.POST.__contains__("remoteShutdown")==True and request.POST['remoteShutdown'] == 'True':
            print "remoteShutdown"
            import os
            userLogInstance = userLog(user= request.user,target=u'系统',content=u'远程关机')
            userLogInstance.save()
            os.system("shutdown -s -t 00")
            return HttpResponseRedirect('/sdt-hts/')
        if request.POST.__contains__("remoteRestart")==True and request.POST['remoteRestart'] == 'True':
            print "remoteRestart"
            import os
            userLogInstance = userLog(user= request.user,target=u'系统',content=u'远程重启')
            userLogInstance.save()
            os.system("shutdown -r -t 00")
            return HttpResponseRedirect('/sdt-hts/')
        if request.POST.__contains__("initTVS")==True and request.POST['initTVS'] == 'True':
            print "initTVS"
            import os
            import subprocess
            os.chdir("/home/sdt/workspace/lTvsWeb")
            print subprocess.Popen("/usr/bin/python hvsInit.py",stdout=subprocess.PIPE, shell=True)
        if request.POST.__contains__("start1")==True and request.POST['start1'] == 'True':
            print "start1"
            # start window 1
            import os
            import subprocess
            os.chdir("/home/sdt/workspace/lTvsWeb")
            window1 = channel.objects.get(pk=int(1))
            window1.inUse = True
            window1.save()
            print subprocess.Popen("/usr/bin/python hvsInit.py",stdout=subprocess.PIPE, shell=True)

        if request.POST.__contains__("start2")==True and request.POST['start2'] == 'True':
            print "start2"
            # start window 1
            import os
            import subprocess
            os.chdir("/home/sdt/workspace/lTvsWeb")
            window1 = channel.objects.get(pk=int(2))
            window1.inUse = True
            window1.save()
            print subprocess.Popen("/usr/bin/python hvsInit.py",stdout=subprocess.PIPE, shell=True)
        if request.POST.__contains__("end1")==True and request.POST['end1'] == 'True':
            print "end1"
            # start window 1
            import os
            import subprocess
            os.chdir("/home/sdt/workspace/lTvsWeb")
            window1 = channel.objects.get(pk=int(1))
            window1.inUse = False
            window1.save()
            print subprocess.Popen("/usr/bin/python hvsInit.py",stdout=subprocess.PIPE, shell=True)
        if request.POST.__contains__("end2")==True and request.POST['end2'] == 'True':
            print "end2"
            # start window 1
            import os
            import subprocess
            os.chdir("/home/sdt/workspace/lTvsWeb")
            window2 = channel.objects.get(pk=int(2))
            window2.inUse = False
            window2.save()
            print subprocess.Popen("/usr/bin/python hvsInit.py",stdout=subprocess.PIPE, shell=True)
        if request.POST.__contains__("start3")==True and request.POST['start3'] == 'True':
            print "start3"
            import os
            import subprocess
            os.chdir("C:/deploy/player")
            print  os.system("start /MIN player3.exe")
        if request.POST.__contains__("start4")==True and request.POST['start4'] == 'True':
            print "start4"
            import os
            import subprocess
            os.chdir("C:/deploy/player")
            print  os.system("start /MIN player4.exe")
        if request.POST.__contains__("end3")==True and request.POST['end3'] == 'True':
            print "end3"
            import os
            os.system('taskkill /f /im "player3.exe"')
        if request.POST.__contains__("end4")==True and request.POST['end4'] == 'True':
            print "end4"
            import os
            os.system('taskkill /f /im "player4.exe"')
        if request.POST.__contains__("startDecoder")==True and request.POST['startDecoder'] == 'True':
            print "startDecoder"
            import os
            import subprocess
            os.chdir("C:/Users/Administrator/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup")
            print subprocess.Popen("decoder.bat")
            sleep(1)
            # os.chdir("C:/hvs/")
            # print subprocess.Popen("startDecoder.bat")
        if request.POST.__contains__("endDecoder")==True and request.POST['endDecoder'] == 'True':
            print "endDecoder"
            import os
            os.system('taskkill /f /im "decoder.exe"')
        if request.POST.__contains__("cleanDB")==True and request.POST['cleanDB'] == 'True':
            terminalArray.objects.all().delete()
            channel.objects.all().delete()
            terminal.objects.all().delete()
            userLog.objects.all().delete()
            packetsLostInfo.objects.all().delete()
            packetGrepper.objects.all().delete()
            debugStatus.objects.all().delete()
            userLogInstance = userLog(user= request.user,target=u'系统',content=u'清空数据库')
            userLogInstance.save()

    return render(request,'config/configSystem.html')

@login_required
@csrf_exempt
def logView(request):
    ulList = userLog.objects.order_by('-pk')[0:100]
    debugStatusInstance = debugStatus.objects.get_or_create(pk=1)[0]
    return render(request,'config/log.html',{'ulList':ulList,'debugStatus':debugStatusInstance})

@login_required
@csrf_exempt
def clearUserLog(request):
    userLog.objects.all().delete()
    userLogInstance = userLog(user= request.user,target=u'用户日志',content=u'清除')
    userLogInstance.save()
    return HttpResponse("success")

import csv

templates/config/configAdapter.html
{% extends "base.html" %}

{% block javascript %}
<script src="/static/js/channels.js"></script>
{% endblock %}
{% block repositories_current %}current{% endblock %}
{% block content %}

<div class="notification success png_bg" id="successMessageBox">
	<a href="#" class="close"><img src="/static/images/icons/cross_grey_small.png" title="Close this notification" alt="close" /></a>
	<div id="successMessage">
	</div>
</div>	
<div class="notification error png_bg" id="errorMessageBox">
	<a href="#" class="close"><img src="/static/images/icons/cross_grey_small.png" title="Close this notification" alt="close" /></a>
	<div id="errorMessage">
	</div>
</div>

<div class="clear"></div>

<table>
	<tr>
		{% ifequal networkAdapter1 None %}

		{% else %}
		<td>
			<div class="content-box" style="min-width:300px;"><!-- Start Content Add repo -->

				<div class="content-box-header">

					<h3>网卡1</h3>

					<div class="clear"></div>

				</div> <!-- End .content-box-header -->

				<div class="content-box-content">
					<form id="formCreateChannel"  action="/sdt-hts/configAdapter/" role="form" method="post">
						<fieldset> <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
							{% csrf_token %}

							<p>
								<h2>{{networkAdapter1.Description.value}}</h2>
								<h7 hidden="hidden">{{networkAdapter1.Description}}</h7>
								<h7 hidden="hidden">{{networkAdapter1.Index}}</h7>
							</p>									
							<p>
								<label>IP地址*:{{networkAdapter1.IP.errors}}</label>
								{{networkAdapter1.IP}}
							</p>
							<p>
								<label>子网掩码*:{{networkAdapter1.IPSubnet.errors}}</label>
								{{networkAdapter1.IPSubnet}}
							</p>
							<p>
								<label>网关*:{{networkAdapter1.DefaultIPGateway.errors}}</label>
								{{networkAdapter1.DefaultIPGateway}}
							</p>																																					
							<p>
								<input id="btnCreateChannel1" class="button" type="submit" value="保存" />
							</p>

						</fieldset>

						<div class="clear"></div><!-- End .clear -->		


					</form>
				</div> <!-- End .content-box-content -->

			</div> <!-- End .content-box -->
		</td>
		{% endifequal %}
		{% ifequal networkAdapter2 None %}

		{% else %}		
		<td>
			<div class="content-box" style="min-width:300px;"><!-- Start Content Add repo -->

				<div class="content-box-header">

					<h3>网卡2</h3>

					<div class="clear"></div>

				</div> <!-- End .content-box-header -->

				<div class="content-box-content">
					<form id="formCreateChannel"  action="/sdt-hts/configAdapter/" role="form" method="post">
						<fieldset> <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
							{% csrf_token %}

							<p>
								<h2>{{networkAdapter2.Description.value}}</h2>
								<h7 hidden="hidden">{{networkAdapter2.Description}}</h7>
								<h7 hidden="hidden">{{networkAdapter2.Index}}</h7>								
							</p>									
							<p>
								<label>IP地址*:{{networkAdapter2.IP.errors}}</label>
								{{networkAdapter2.IP}}
							</p>
							<p>
								<label>子网掩码*:{{networkAdapter2.IPSubnet.errors}}</label>
								{{networkAdapter2.IPSubnet}}
							</p>
							<p>
								<label>网关*:{{networkAdapter2.DefaultIPGateway.errors}}</label>
								{{networkAdapter2.DefaultIPGateway}}
							</p>																																						
							<p>
								<input id="btnCreateChannel1" class="button" type="submit" value="保存" />
							</p>
							
						</fieldset>
						
						<div class="clear"></div><!-- End .clear -->		
						

					</form>

				</div> <!-- End .content-box-content -->

			</div> <!-- End .content-box -->

		</td>
		{% endifequal %}		
	</tr>
</table>







{% endblock %}

templates/config/configPacketGrepper.html
{% extends "base.html" %}

{% block javascript %}
<script src="/static/js/channels.js"></script>
<script src="/static/js/common.js"></script>
{% endblock %}
{% block repositories_current %}current{% endblock %}
{% block content %}
<link rel="stylesheet" type="text/css" href="/static/easyui.css">
<link rel="stylesheet" type="text/css" href="/static/icon.css">
<link rel="stylesheet" type="text/css" href="/static/demo.css">
<link rel="stylesheet" type="text/css" href="/static/themes/color.css">
<!-- <script type="text/javascript" src="/static/jquery.min.js"></script> -->
<script type="text/javascript" src="/static/jquery.easyui.min.js"></script>


<div class="content-box" style="min-width:300px;"><!-- Start Content Add repo -->

	<div class="content-box-header">

		<h3>配置抓包服务器</h3>

		<div class="clear"></div>

	</div> <!-- End .content-box-header -->

	<div class="content-box-content">

		<table>
			<tr>
				
	
					<td style="width:15%">是否启用抓包服务器:</td>
					<td style="width:10%"><input class="easyui-switchbutton" onText="开" offText="关" id="packetGrepper" {% ifequal packetGrepper.active True %} checked {% endifequal %}   ></td>
					<td style="width:35%"> <label> 抓包服务器IP*: </label><input class="text-input small-input" id="id_ip" maxlength="200" name="ip" type="text" value="{{packetGrepper.ip}}"> </input> </td>
					<td >
					<a onclick="pushToDjango()" value="保存" class="easyui-linkbutton c6" style="width:120px;float:center">保存</a>
					</td>
			
			
			</tr>
		</table>


	</div> <!-- End .content-box-content -->

</div> <!-- End .content-box -->







{% endblock %}

templates/config/getMonitorInfo.html
{% extends "base.html" %}

{% block javascript %}
<script src="/static/js/getMonitorInfo.js"></script>
{% endblock %}
{% block repositories_current %}current{% endblock %}
{% block content %}

<link rel="stylesheet" type="text/css" href="/static/easyui.css">
<link rel="stylesheet" type="text/css" href="/static/icon.css">
<link rel="stylesheet" type="text/css" href="/static/demo.css">
<link rel="stylesheet" type="text/css" href="/static/themes/color.css">
<!-- <script type="text/javascript" src="/static/jquery.min.js"></script> -->
<script type="text/javascript" src="/static/jquery.easyui.min.js"></script>



<div class="notification success png_bg" id="successMessageBox">
	<a href="#" class="close"><img src="/static/images/icons/cross_grey_small.png" title="Close this notification" alt="close" /></a>
	<div id="successMessage">
	</div>
</div>	
<div class="notification error png_bg" id="errorMessageBox">
	<a href="#" class="close"><img src="/static/images/icons/cross_grey_small.png" title="Close this notification" alt="close" /></a>
	<div id="errorMessage">
	</div>
</div>

<div class="clear"></div>

<div class="content-box"><!-- Start Content Add repo -->

	<div class="content-box-header">

		<h3>显示器信息</h3>

		<div class="clear"></div>

	</div> <!-- End .content-box-header -->
	
	<div class="content-box-content">

		<table>
			
			<thead>
				<tr>
					<th>ID</th>
					<th>所在GPU</th>
					<th>显示器名称</th>
					<th>分辨率</th>
					<th>刷新率</th>
					<th>inUse</th>
				</tr>
				
			</thead>

			<tbody id="channelList">
				
				{% for channel in channels %}
				<tr>
					<td>{{channel.id}}</td>
					<td>{{channel.GPUSeq}}</td>
					<td>{{channel.name}}</td>
					<td>{{channel.resolution}}</td>
					<td>{{channel.freshRate}}</td>
					<td>{{channel.inUse}}</td>
				</tr>
				{% endfor %}
				
			</tbody>
			
		</table>

		<p>
			<input id="getMonitorInfo" class="button" type="submit" value="获取显示设备信息" />
		</p>


	</div> <!-- End .content-box-content -->

</div> <!-- End .content-box -->		





{% endblock %}

templates/config/lisense.html
{% extends "base.html" %}

{% block javascript %}
<script src="/static/js/channels.js"></script>
<!-- <script src="/static/bootstrap/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.min.css"> -->
<link rel="stylesheet" type="text/css" href="/static/easyui.css">
<link rel="stylesheet" type="text/css" href="/static/icon.css">
<link rel="stylesheet" type="text/css" href="/static/demo.css">
<link rel="stylesheet" type="text/css" href="/static/themes/color.css">
<!-- <script type="text/javascript" src="/static/jquery.min.js"></script> -->
<script type="text/javascript" src="/static/jquery.easyui.min.js"></script>
{% endblock %}

{% block content %}
<div class="clear"></div>

<div class="content-box" style="width:1100px;"><!-- Start Content Add repo -->

	<div class="content-box-header">
	<h3>授权管理</h3>
	<div class="clear"></div>
	</div> <!-- End .content-box-header -->
	<div class="content-box-content" >
	<h4> 系统注册状态：{{registerStatus}} </h4>
	{% ifequal registerStatus "未注册" %}
		<h5> 请将机器码提交管理员获取license文件：{{hdSerial}} </h5>
		<form enctype="multipart/form-data" method="post" action="/sdt-hts/license/">
		{% csrf_token %}
		<!-- {{uploadFileForm}} -->
		<input class="easyui-filebox" name='file' data-options="prompt:'请选择license文件'" style="width:30%">
			<!-- <input type="file" name="file"/><br/> -->
			<input type="submit" value="上传文件"/>

		</form>
	{% else %}

	{% endifequal %}
	</div> <!-- End .content-box-content -->
</div> <!-- End .content-box -->

<script type="text/javascript">
$(document).ready(function(){
	var msg = "{{msg}}";

	if (msg == "error"){
					$.messager.show({
						title:'警告!',
						msg:"{{msgContent}}",
						timeout:5000,
						showType:'slide',
					});		
	}
	else if(msg=="success"){
					$.messager.show({
						title:'通知!',
						msg:"{{msgContent}}",
						timeout:5000,
						showType:'slide',
					});			
	}
	else if(msg!=""){
					$.messager.show({
						title:'通知!',
						msg:msg,
						timeout:5000,
						showType:'slide',
					});		
	}


		
})

</script>
{% endblock %}

templates/config/packetInfo.html
{% extends "base.html" %}

{% block javascript %}
<script src="/static/js/channels.js"></script>
{% endblock %}
{% block repositories_current %}current{% endblock %}
{% block content %}

<link rel="stylesheet" type="text/css" href="/static/easyui.css">
<link rel="stylesheet" type="text/css" href="/static/icon.css">
<link rel="stylesheet" type="text/css" href="/static/demo.css">
<link rel="stylesheet" type="text/css" href="/static/themes/color.css">
<!-- <script type="text/javascript" src="/static/jquery.min.js"></script> -->
<script type="text/javascript" src="/static/jquery.easyui.min.js"></script>


<div class="clear"></div>

<div class="content-box" style="width:1100px;"><!-- Start Content Add repo -->

	<div class="content-box-header">

		<h3>丢包检测</h3>

		<div class="clear"></div>

	</div> <!-- End .content-box-header -->
	
	<div class="content-box-content" >

		<div style="margin:20px 0;"></div>
		<table style="border:1px solid #98bf21">

			<thead>
				<tr>

					<th>终端名</th>
					<th>最后一次丢包时间</th>
					<th>丢包数</th>
					<th>总包数</th>
				</tr>

			</thead>

			<tbody id="packetInfos">


			</tbody>

		</table>
	
</div> <!-- End .content-box-content -->

</div> <!-- End .content-box -->	

<script type="text/javascript">
	
	
	function getPacketInfo(){
		$.get('/sdt-hts/packetInfo/', function(packetInfoList){
			$("#packetInfos").html('');
			var i = 0;
			var j = 0;
			var textToInsert = [];	
			for(i; i < packetInfoList.length; i++){
				textToInsert[j++] = '<tr class=' + packetInfoList[i].pk + '>';
				textToInsert[j++] = '<td>' + packetInfoList[i].fields.terminalName + '</td>\n';
				textToInsert[j++] = '<td>' + packetInfoList[i].fields.latestLostDate + '</td>\n';
				textToInsert[j++] = '<td>' + packetInfoList[i].fields.lostNumbers + '</td>\n';
				textToInsert[j++] = '<td>' + packetInfoList[i].fields.totalPacketNumbers + '</td>\n';
				textToInsert[j++] = '</tr>\n';			
			}
			$('#packetInfos').append(textToInsert.join(''));			
		}, "json");
	};
	getPacketInfo();
	setInterval(getPacketInfo,4000);
</script>

{% endblock %}

templates/config/textStyle.html
{% extends "base.html" %}

{% block javascript %}
<script src="/static/js/channels.js"></script>
<link rel="stylesheet" type="text/css" href="/static/easyui.css">
<link rel="stylesheet" type="text/css" href="/static/icon.css">
<link rel="stylesheet" type="text/css" href="/static/demo.css">
<link rel="stylesheet" type="text/css" href="/static/themes/color.css">
<!-- <script type="text/javascript" src="/static/jquery.min.js"></script> -->
<script type="text/javascript" src="/static/jquery.easyui.min.js"></script>
{% endblock %}

{% block content %}
<div class="clear"></div>

<div class="content-box" style="width:1100px;"><!-- Start Content Add repo -->

	<div class="content-box-header">
	<h3>wenzishezhi</h3>
	<div class="clear"></div>
	</div> <!-- End .content-box-header -->
	<div class="content-box-content" >
		<form enctype="multipart/form-data" method="post" action="/sdt-hts/textStyle/">
		{% csrf_token %}
		{{form}}
		<input type="submit" value="上传文件"/>
		</form>
	</div> <!-- End .content-box-content -->
</div> <!-- End .content-box -->

<script type="text/javascript">
$(document).ready(function(){
	var msg = "{{msg}}";

	if (msg == "error"){
					$.messager.show({
						title:'警告!',
						msg:"{{msgContent}}",
						timeout:5000,
						showType:'slide',
					});
	}
	else if(msg=="success"){
					$.messager.show({
						title:'通知!',
						msg:"{{msgContent}}",
						timeout:5000,
						showType:'slide',
					});
	}
	else if(msg!=""){
					$.messager.show({
						title:'通知!',
						msg:msg,
						timeout:5000,
						showType:'slide',
					});
	}
})

</script>
{% endblock %}